// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StudentApplicationManagementSystem.Models;

[Table("application_status")]
public partial class ApplicationStatus
{
    [Key]
    [Column("application_status_id")]
    public int ApplicationStatusId { get; set; }

    [Required]
    [Column("application_status_name")]
    public string ApplicationStatusName { get; set; }

    [InverseProperty("StudentApplicationStatus")]
    public virtual ICollection<StudentApplication> StudentApplications { get; set; } = new List<StudentApplication>();
}