// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StudentApplicationManagementSystem.Models;

[Table("applicant")]
public partial class Applicant
{
    [Key]
    [Column("applicant_id")]
    public int ApplicantId { get; set; }

    [Required]
    [Column("applicant_surname")]
    public string ApplicantSurname { get; set; }

    [Required]
    [Column("applicant_name")]
    public string ApplicantName { get; set; }

    [Column("applicant_patronymic")]
    public string ApplicantPatronymic { get; set; }

    [Required]
    [Column("applicant_telephone")]
    public string ApplicantTelephone { get; set; }

    [InverseProperty("Student")]
    public virtual ICollection<StudentApplication> StudentApplications { get; set; } = new List<StudentApplication>();
}