// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StudentApplicationManagementSystem.Models;

[Table("degree")]
public partial class Degree
{
    [Key]
    [Column("degree_id")]
    public int DegreeId { get; set; }

    [Required]
    [Column("degree_name")]
    public string DegreeName { get; set; }

    [InverseProperty("SpecialtyDegree")]
    public virtual ICollection<Specialty> Specialties { get; set; } = new List<Specialty>();
}