// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StudentApplicationManagementSystem.Models;

[Table("funding_type")]
public partial class FundingType
{
    [Key]
    [Column("funding_type_id")]
    public int FundingTypeId { get; set; }

    [Required]
    [Column("funding_type_name")]
    public string FundingTypeName { get; set; }

    [InverseProperty("FundingType")]
    public virtual ICollection<StudentApplication> StudentApplications { get; set; } = new List<StudentApplication>();
}