// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StudentApplicationManagementSystem.Models;

[Table("specialty")]
[Index("SpecialtyUniversityId", Name = "fki_fk_university_id")]
public partial class Specialty
{
    [Key]
    [Column("specialty_id")]
    public int SpecialtyId { get; set; }

    [Required]
    [Column("specialty_name")]
    public string SpecialtyName { get; set; }

    [Column("specialty_university_id")]
    public int SpecialtyUniversityId { get; set; }

    [Column("specialty_degree_id")]
    public int SpecialtyDegreeId { get; set; }

    [Column("specialty_budget_spots")]
    public int SpecialtyBudgetSpots { get; set; }

    [Column("specialty_total_spots")]
    public int SpecialtyTotalSpots { get; set; }

    [ForeignKey("SpecialtyDegreeId")]
    [InverseProperty("Specialties")]
    public virtual Degree SpecialtyDegree { get; set; }

    [ForeignKey("SpecialtyUniversityId")]
    [InverseProperty("Specialties")]
    public virtual University SpecialtyUniversity { get; set; }

    [InverseProperty("StudentApplicationSpecialty")]
    public virtual ICollection<StudentApplication> StudentApplications { get; set; } = new List<StudentApplication>();
}