// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StudentApplicationManagementSystem.Models;

[Table("student_application")]
[Index("FundingTypeId", Name = "fki_fk_funding_type")]
public partial class StudentApplication
{
    [Key]
    [Column("student_application_id")]
    public int StudentApplicationId { get; set; }

    [Column("student_id")]
    public int StudentId { get; set; }

    [Column("student_application_score")]
    public double StudentApplicationScore { get; set; }

    [Column("student_application_university_id")]
    public int StudentApplicationUniversityId { get; set; }

    [Column("student_application_status_id")]
    public int StudentApplicationStatusId { get; set; } = 1;

    [Column("student_application_priority")]
    public int StudentApplicationPriority { get; set; }

    [Column("student_application_specialty_id")]
    public int StudentApplicationSpecialtyId { get; set; }

    [Column("funding_type_id")]
    public int FundingTypeId { get; set; }

    [ForeignKey("FundingTypeId")]
    [InverseProperty("StudentApplications")]
    public virtual FundingType FundingType { get; set; }

    [ForeignKey("StudentId")]
    [InverseProperty("StudentApplications")]
    public virtual Applicant Student { get; set; }

    [ForeignKey("StudentApplicationSpecialtyId")]
    [InverseProperty("StudentApplications")]
    public virtual Specialty StudentApplicationSpecialty { get; set; }

    [ForeignKey("StudentApplicationStatusId")]
    [InverseProperty("StudentApplications")]
    public virtual ApplicationStatus StudentApplicationStatus { get; set; }

    [ForeignKey("StudentApplicationUniversityId")]
    [InverseProperty("StudentApplications")]
    public virtual University StudentApplicationUniversity { get; set; }
}