// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StudentApplicationManagementSystem.Models;

[Table("university")]
public partial class University
{
    [Key]
    [Column("university_id")]
    public int UniversityId { get; set; }

    [Required]
    [Column("university_name")]
    public string UniversityName { get; set; }

    [InverseProperty("SpecialtyUniversity")]
    public virtual ICollection<Specialty> Specialties { get; set; } = new List<Specialty>();

    [InverseProperty("StudentApplicationUniversity")]
    public virtual ICollection<StudentApplication> StudentApplications { get; set; } = new List<StudentApplication>();
}